name: Sample Application CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        tags: my-docker-image:latest

    - name: Publish Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: my-docker-image:latest

    - name: Deploy to production
      if: github.ref == 'refs/heads/main'
      uses: some/deployment-action@v1
      with:
        environment: production